import type { AdminPermission } from "./capabilities";

/**
 * Test-only matrix mirror of ADMIN_PERMISSION_MATRIX.md seed grants.
 * Production authorization loads grants from the database.
 */
export const TEST_ROLE_PERMISSIONS: Readonly<Record<string, readonly AdminPermission[]>> = {
  super_admin: [
    "customers.read",
    "customers.update",
    "customers.suspend",
    "customers.notes",
    "customers.kyc",
    "deposits.read",
    "deposits.review",
    "deposits.approve",
    "withdrawals.read",
    "withdrawals.review",
    "withdrawals.approve",
    "investments.read",
    "investments.update",
    "settlements.read",
    "settlements.manage",
    "reports.read",
    "reports.export",
    "emails.manage",
    "notifications.manage",
    "featureflags.manage",
    "system.manage",
    "roles.manage",
    "permissions.manage",
    "staff.manage",
    "staff.reset_password",
    "audit.read",
    "jobs.manage",
    "security.read",
    "monitoring.read",
    "overview.read",
  ],
  platform_admin: [
    "customers.read",
    "customers.update",
    "customers.suspend",
    "customers.notes",
    "customers.kyc",
    "deposits.read",
    "deposits.review",
    "deposits.approve",
    "withdrawals.read",
    "withdrawals.review",
    "withdrawals.approve",
    "investments.read",
    "investments.update",
    "settlements.read",
    "settlements.manage",
    "reports.read",
    "reports.export",
    "emails.manage",
    "notifications.manage",
    "featureflags.manage",
    "system.manage",
    "roles.manage",
    "permissions.manage",
    "staff.manage",
    "staff.reset_password",
    "audit.read",
    "jobs.manage",
    "security.read",
    "monitoring.read",
    "overview.read",
  ],
  finance_admin: [
    "customers.read",
    "deposits.read",
    "deposits.review",
    "deposits.approve",
    "withdrawals.read",
    "withdrawals.review",
    "withdrawals.approve",
    "investments.read",
    "settlements.read",
    "reports.read",
    "reports.export",
    "audit.read",
    "jobs.manage",
    "monitoring.read",
    "overview.read",
  ],
  finance_manager: [
    "customers.read",
    "deposits.read",
    "deposits.review",
    "deposits.approve",
    "withdrawals.read",
    "withdrawals.review",
    "withdrawals.approve",
    "investments.read",
    "settlements.read",
    "reports.read",
    "reports.export",
    "audit.read",
    "jobs.manage",
    "monitoring.read",
    "overview.read",
  ],
  support_agent: [
    "customers.read",
    "customers.notes",
    "deposits.read",
    "withdrawals.read",
    "investments.read",
    "overview.read",
  ],
  compliance_officer: [
    "customers.read",
    "customers.update",
    "customers.suspend",
    "customers.notes",
    "customers.kyc",
    "deposits.read",
    "withdrawals.read",
    "investments.read",
    "reports.read",
    "reports.export",
    "audit.read",
    "security.read",
    "overview.read",
  ],
  auditor: [
    "customers.read",
    "deposits.read",
    "withdrawals.read",
    "investments.read",
    "settlements.read",
    "reports.read",
    "audit.read",
    "security.read",
    "monitoring.read",
    "overview.read",
  ],
  read_only: [
    "customers.read",
    "deposits.read",
    "withdrawals.read",
    "investments.read",
    "settlements.read",
    "reports.read",
    "monitoring.read",
    "overview.read",
  ],
};

export function permissionKeysForRoles(roleKeys: readonly string[]): string[] {
  const keys = new Set<string>();
  for (const roleKey of roleKeys) {
    for (const permission of TEST_ROLE_PERMISSIONS[roleKey] ?? []) {
      keys.add(permission);
    }
  }
  return [...keys];
}
