export const designTokens = {
  spacing: {
    0: "0",
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
    16: "4rem",
    20: "5rem",
    24: "6rem",
  },
  typography: {
    caption: "0.75rem",
    body: "0.875rem",
    lead: "1rem",
    title: "1.25rem",
    display: "2.5rem",
  },
  radius: {
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
  },
  elevation: {
    1: "var(--elevation-1)",
    2: "var(--elevation-2)",
    3: "var(--elevation-3)",
  },
  colors: {
    success: "var(--success)",
    warning: "var(--warning)",
    error: "var(--destructive)",
    information: "var(--info)",
    roiPositive: "var(--roi-positive)",
    roiPending: "var(--roi-pending)",
    financialPositive: "var(--financial-positive)",
    financialNegative: "var(--financial-negative)",
    financialNeutral: "var(--financial-neutral)",
  },
  motion: {
    fast: "var(--duration-fast)",
    standard: "var(--duration-standard)",
    slow: "var(--duration-slow)",
    easing: "var(--ease-standard)",
  },
  zIndex: {
    base: "var(--z-base)",
    dropdown: "var(--z-dropdown)",
    sticky: "var(--z-sticky)",
    overlay: "var(--z-overlay)",
    modal: "var(--z-modal)",
    toast: "var(--z-toast)",
  },
  breakpoints: {
    sm: "40rem",
    md: "48rem",
    lg: "64rem",
    xl: "80rem",
    "2xl": "96rem",
  },
  containers: {
    sm: "40rem",
    md: "48rem",
    lg: "64rem",
    xl: "80rem",
    page: "90rem",
  },
} as const;

export type DesignTokens = typeof designTokens;
