export const APP_ERROR_CODES = [
  "VALIDATION_ERROR",
  "AUTHENTICATION_ERROR",
  "AUTHORIZATION_ERROR",
  "NOT_FOUND",
  "CONFLICT",
  "INVALID_STATE",
  "IDEMPOTENCY_ERROR",
  "RATE_LIMITED",
  "PROVIDER_ERROR",
  "FINANCIAL_INTEGRITY_ERROR",
  "INTERNAL_ERROR",
] as const;

export type AppErrorCode = (typeof APP_ERROR_CODES)[number];
